[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2018"
name = "panoptes-validator"
description = "Panoptes blockchain, Rebuilt for Scale"
version = "1.7.3"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/panoptes-validator"
default-run = "panoptes-validator"

[dependencies]
base64 = "0.12.3"
bincode = "1.3.1"
chrono = { version = "0.4.11", features = ["serde"] }
clap = "2.33.1"
console = "0.14.1"
core_affinity = "0.5.10"
fd-lock = "2.0.0"
indicatif = "0.15.0"
jsonrpc-core = "17.1.0"
jsonrpc-core-client = { version = "17.1.0", features = ["ipc", "ws"] }
jsonrpc-derive = "17.1.0"
jsonrpc-ipc-server = "17.1.0"
jsonrpc-server-utils= "17.1.0"
log = "0.4.11"
num_cpus = "1.13.0"
rand = "0.7.0"
serde = "1.0.112"
solana-clap-utils = { path = "../clap-utils", version = "=1.7.3" }
solana-cli-config = { path = "../cli-config", version = "=1.7.3" }
solana-client = { path = "../client", version = "=1.7.3" }
solana-core = { path = "../core", version = "=1.7.3" }
solana-download-utils = { path = "../download-utils", version = "=1.7.3" }
panoptes-faucet = { path = "../faucet", version = "=1.7.3" }
solana-genesis-utils = { path = "../genesis-utils", version = "=1.7.3" }
solana-gossip = { path = "../gossip", version = "=1.7.3" }
solana-ledger = { path = "../ledger", version = "=1.7.3" }
solana-logger = { path = "../logger", version = "=1.7.3" }
solana-metrics = { path = "../metrics", version = "=1.7.3" }
solana-net-utils = { path = "../net-utils", version = "=1.7.3" }
solana-perf = { path = "../perf", version = "=1.7.3" }
solana-poh = { path = "../poh", version = "=1.7.3" }
solana-rpc = { path = "../rpc", version = "=1.7.3" }
solana-runtime = { path = "../runtime", version = "=1.7.3" }
solana-sdk = { path = "../sdk", version = "=1.7.3" }
solana-version = { path = "../version", version = "=1.7.3" }
solana-vote-program = { path = "../programs/vote", version = "=1.7.3" }
symlink = "0.1.0"

[target."cfg(unix)".dependencies]
libc = "0.2.81"
signal-hook = "0.1.15"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
