[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2018"
name = "solana-poh-bench"
version = "1.7.3"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-poh-bench"

[dependencies]
clap = "2.33.1"
log = "0.4.11"
rand = "0.7.0"
rayon = "1.5.0"
solana-logger = { path = "../logger", version = "=1.7.3" }
solana-ledger = { path = "../ledger", version = "=1.7.3" }
solana-sdk = { path = "../sdk", version = "=1.7.3" }
solana-clap-utils = { path = "../clap-utils", version = "=1.7.3" }
solana-measure = { path = "../measure", version = "=1.7.3" }
solana-version = { path = "../version", version = "=1.7.3" }
solana-perf = { path = "../perf", version = "=1.7.3" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
