[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2018"
name = "panoptes-stake-monitor"
description = "Panoptes blockchain, Rebuilt for Scale"
version = "1.7.3"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-stake-monitor"

[dependencies]
clap = "2.33.1"
console = "0.14.1"
log = "0.4.11"
serde = "1.0.122"
serde_yaml = "0.8.13"
solana-clap-utils = { path = "../clap-utils", version = "=1.7.3" }
solana-cli-config = { path = "../cli-config", version = "=1.7.3" }
solana-client = { path = "../client", version = "=1.7.3" }
solana-logger = { path = "../logger", version = "=1.7.3" }
solana-metrics = { path = "../metrics", version = "=1.7.3" }
solana-rpc = { path = "../rpc", version = "=1.7.3" }
solana-sdk = { path = "../sdk", version = "=1.7.3" }
solana-transaction-status = { path = "../transaction-status", version = "=1.7.3" }
solana-version = { path = "../version", version = "=1.7.3" }

[dev-dependencies]
serial_test = "0.4.0"
solana-local-cluster = { path = "../local-cluster", version = "=1.7.3" }
solana-core = { path = "../core", version = "=1.7.3" }
tempfile = "3.1.0"

[[bin]]
name = "panoptes-stake-monitor"
path = "src/main.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
