[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
description = "Panoptes Program Test Framework"
edition = "2018"
license = "Apache-2.0"
name = "solana-program-test"
repository = "https://github.com/solana-labs/solana"
version = "1.7.3"

[dependencies]
async-trait = "0.1.42"
base64 = "0.12.3"
bincode = "1.3.1"
chrono = "0.4.19"
chrono-humanize = "0.2.1"
log = "0.4.11"
mio = "0.7.6"
serde = "1.0.112"
serde_derive = "1.0.103"
solana-banks-client = { path = "../banks-client", version = "=1.7.3" }
solana-banks-server = { path = "../banks-server", version = "=1.7.3" }
solana-bpf-loader-program = { path = "../programs/bpf_loader", version = "=1.7.3" }
solana-logger = { path = "../logger", version = "=1.7.3" }
solana-runtime = { path = "../runtime", version = "=1.7.3" }
solana-sdk = { path = "../sdk", version = "=1.7.3" }
solana-vote-program = { path = "../programs/vote", version = "=1.7.3" }
thiserror = "1.0"
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
assert_matches = "1.3.0"
